Update and rename eel-players.yml to epl-players.yml

diff --git a/.github/workflows/epl-players.yml b/.github/workflows/epl-players.yml
--- a/.github/workflows/epl-players.yml
+++ b/.github/workflows/epl-players.yml
@@ -16,10 +16,29 @@ jobs:
         with:
           python-version: "3.11"
 
-      - name: Build EPL Players
+      - name: Verify Files
+        run: |
+          echo "ROOT FILES:"
+          ls
+
+          echo "SCRIPTS FOLDER:"
+          ls scripts || true
+
+      - name: Run EPL Player Builder
         run: |
 
-          python build_epl_players.py
+          if [ -f build_epl_players.py ]; then
+            echo "FOUND ROOT SCRIPT"
+            python build_epl_players.py
+
+          elif [ -f scripts/build_epl_players.py ]; then
+            echo "FOUND SCRIPTS VERSION"
+            python scripts/build_epl_players.py
+
+          else
+            echo "SCRIPT NOT FOUND"
+            exit 1
+          fi
 
       - name: Commit Changes
         run: |
